name: Jennifer Holly Lee
favicon: null
layout_spectrum: 0.7906840636860579
typography_spectrum: 0.15684823808260262
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.1345612946897745
  lightness: 0.015755648724734783
  saturation: 0.9566974486224353
  rhythmicContrast: 0.22520769340917468
purpose: []
